# Generated by Django 4.1 on 2022-08-24 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='bookmark',
            field=models.ManyToManyField(blank=True, null=True, related_name='bookmark_game', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_joined',
            field=models.ManyToManyField(blank=True, null=True, related_name='joined_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='request_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='request_joined_player', to=settings.AUTH_USER_MODEL),
        ),
    ]
