# Generated by Django 4.1 on 2022-08-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_bookmark_alter_game_player_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='court_price',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='court_status',
            field=models.CharField(blank=True, choices=[('Book', 'Book'), ('Not Book', 'Not book')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='price_per_player',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
